---
services:
  mtapiclient:
    image: mtapiclient:0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    container_name: mtApiClient
    read_only: true
    labels:
      com.sensiaglobal.image.config_manager_reg_name: mtApiClient
    restart: on-failure  
    networks:
      - network1
    ports:
      - '5202:5202'
    environment:
      CLIENT: "Client1"
      API_HOST: "mtApi"
      API_SUFFIX: "api/v1"
      API_PROTOCOL: "http"
      API_PORT: 5236
      TIME_PERIOD: 10
      WH_HOST: "192.168.1.71"
      WH_SUFFIX: "api/v1"
      WH_PROTOCOL: "http"
      WH_PORT: 8002
      ON_TIME: 20000
      OFF_TIME: 20000
    tmpfs:
      - /tmp:uid=5678,gid=5678

networks:
  network1:
    name: edgenet
    external: true

...
