services:
  mtapi:
    image: sdkapi:0.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    container_name: mtApi
    read_only: true
    labels:
      com.sensiaglobal.image.config_manager_reg_name: mtApi
    restart: on-failure  
    networks:
      - network1
    ports:
      - '5202:5202'
    environment:
      ZMQ_HOST: "zmqproxy"
      API_HOST: "mtapi"
      API_EXPORT_HOST: "mtapi"
      SUB_PORT: 3000
      PUB_PORT: 3001
      REQUEST_PORT: 3002
      RESPONSE_PORT: 3500
    tmpfs:
      - /tmp:uid=5678,gid=5678
    volumes:
      - sdkapi_db_vol:/app/db
networks:
  network1:
    name: edgenet
    external: true

volumes:
  sdkapi_db_vol:
    name: sdkapi_db_vol
...
